dist: trusty
sudo: required

# we don't use it, but we also do not want default (ruby) image
language: go

services:
  - docker

os:
  - windows
  - linux
  - osx

# skip default (go get -t -v ./...) install step
install: true

script: ./travis.sh

addons:
  code_climate:
    repo_token: b3b137f48bcd4e7fc58959706e292888be90f06c51822f6105fe50c0e1502191
